name: Test Automation Workflow
'on':
  schedule:
    - cron: 00 18 * * *
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: temurin
          cache: maven
      - name: Create necessary directories (important!)
        run: >
          mkdir -p logs

          mkdir -p screenshots

          mkdir -p target/surefire-reports # Or wherever your reports go

          touch Automationreport.html # Create an empty file to avoid errors if
          it doesn't exist
      - name: Run Test Automation Framework with Maven
        run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false
      - name: Archive Test Reports (Surefire)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports
      - name: Upload Test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test logs
          path: logs/
      - name: Upload Screenshots as Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/
      - name: Upload HTML Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: Automationreport.html
      - name: Test Execution Status
        if: always()
        run: echo "Test Execution Completed"
      - name: Copy Report to gh-pages Folder
        if: always()
        run: |
          mkdir -p public/extent-reports
          cp Automationreport.html public/extent-reports/
          cp -r screenshots public/extent-reports/
          #Ensure the screenshots directory is copied recursively
          ls -l public/extent-reports/
      - name: Deploy to GitHub Pages
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public/extent-reports
          token: '${{ secrets.PAT1234 }}'
          clean: true
